name: pos_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  dotted_line: ^3.2.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_gen: ^5.10.0
  flutter_staggered_animations: ^1.1.1
  get: ^4.7.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true